routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\QuotationController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DomainController;
use App\Http\Controllers\VendorController;
use App\Http\Controllers\EmailBlastController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\ProjectCategoryController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\EmailSchedulerController;
use App\Http\Controllers\MomController;
use App\Http\Controllers\TncController;

use App\Models\SubCountry;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [LoginController::class, 'index'])->middleware('guest')->name('login');
Route::post('/', [LoginController::class, 'authenticate']);
Route::get('/logout', [LoginController::class, 'logout']);

Route::resource('quotation', QuotationController::class)->middleware('auth');
Route::resource('item', ItemController::class)->middleware('auth');
Route::resource('customer', CustomerController::class)->middleware('auth');
Route::resource('profile', ProfileController::class)->middleware('auth');
Route::resource('domain', DomainController::class)->middleware('auth');
Route::resource('vendor', VendorController::class)->middleware('auth');
Route::resource('email_blast', EmailBlastController::class)->middleware('auth');
Route::resource('email_scheduler', EmailSchedulerController::class)->middleware('auth');
Route::resource('category', CategoryController::class)->middleware('auth');
Route::resource('invoice', InvoiceController::class)->middleware('auth');
Route::resource('dashboard', DashboardController::class)->middleware('auth');
Route::resource('event', EventController::class)->middleware('auth');
Route::resource('employee', EmployeeController::class)->middleware('auth');
Route::resource('project', ProjectController::class)->middleware('auth');
Route::resource('project_category', ProjectCategoryController::class)->middleware('auth');
Route::resource('task', TaskController::class)->middleware('auth');
Route::resource('mom', MomController::class)->middleware('auth');
Route::resource('tnc', TncController::class)->middleware('auth');

Route::get('/email_blast/unsubscribe/{id}', [EmailBlastController::class, 'unsubscribe']);

Route::post('/category-project', [ProjectCategoryController::class, 'getProjectCategory']);
Route::get('/quotation/getCustomer/{id}', [QuotationController::class, 'getCustomer']);
Route::get('/quotation/getPrice/{id}', [QuotationController::class, 'getPrice']);
Route::get('/project/getCustomer/{id}', [ProjectController::class, 'getCustomer']);
Route::get('/print_quotation/{id}', [QuotationController::class, 'printPdf']);
Route::get('/quotation/email/{id}', [QuotationController::class, 'email']);
Route::get('/mom/email/{id}', [MomController::class, 'email']);
Route::get('/print_mom/{id}', [MomController::class, 'printPdf']);


Route::get('/getProvinces', function () {
  return response()->json(SubCountry::whereRaw('length(code) = 2')->orderBy('name')->get());
  
});

Route::get('/getProvince/{id}', function ($id) {
  return response()->json(SubCountry::where('code', $id)->first());
});

Route::get('/getCities/{id}', function ($id) {
  $data = SubCountry::whereRaw('length(code) = 5')
    ->where('code', 'like', $id . '%')
    ->orderBy('name')->get();
  return response()->json($data);
});

Route::get('/getCity/{id}', function ($id) {
  return response()->json(SubCountry::where('code', $id)->first());
});

app/Models/EmailScheduler.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class EmailScheduler extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
    protected $table = 'email_schedulers';

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    public function customerType()
    {
        return $this->belongsTo(CustomerType::class);
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Customer;
use App\Models\Domain;
use App\Models\Vendor;
use App\Models\Employee;
use App\Models\Project;
use App\Models\Quotation;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.dashboard.index', [
            'title' => 'Dashboard',

            'customers' => Customer::all()->count(),
            'domains' => Domain::all()->count(),
            'vendors' => Vendor::all()->count(),
            'staff' => Employee::all()->count(),
            'project' => Project::all()->count(),
            'quotation' => Quotation::all()->count()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/EmailSchedulerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\EmailScheduler;
use App\Models\Customer;
use App\Models\Company;
use App\Models\Category;
use App\Models\CustomerType;
use App\Jobs\SendMailJob;
use App\Mail\NewArrivals;
use Mail;
use Carbon\Carbon;
use Illuminate\Support\Facades\Session;

class EmailSchedulerController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    return view('dashboard.email_scheduler.index', [
      'title' => 'Email scheduler',
      'email_scheduler' => EmailScheduler::orderBy('created_at', 'desc')->get()
    ]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('dashboard.email_scheduler.create', [
      'title' => 'Create Email Scheduler',
      'company' => Company::first(),
      'categories' => Category::all(),
      'customer_type' => CustomerType::all()
    ]);
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
  
    //JIKA ADA DATA YANG DIKIRIMKAN
    if ($request->hasFile('upload')) {
      $file = $request->file('upload'); //SIMPAN SEMENTARA FILENYA KE VARIABLE
      $fileName = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME); //KITA GET ORIGINAL NAME-NYA
      //KEMUDIAN GENERATE NAMA YANG BARU KOMBINASI NAMA FILE + TIME
      $fileName = $fileName . '_' . time() . '.' . $file->getClientOriginalExtension();

      $file->move(public_path('uploads'), $fileName); //SIMPAN KE DALAM FOLDER PUBLIC/UPLOADS

      //KEMUDIAN KITA BUAT RESPONSE KE CKEDITOR
      $ckeditor = $request->input('CKEditorFuncNum');
      $url = asset('uploads/' . $fileName); 
      $msg = 'Image uploaded successfully'; 
      //DENGNA MENGIRIMKAN INFORMASI URL FILE DAN MESSAGE
      $response = "<script>window.parent.CKEDITOR.tools.callFunction($ckeditor, '$url', '$msg')</script>";

      //SET HEADERNYA
      @header('Content-type: text/html; charset=utf-8'); 
      return $response;
    }

    $messages = [
      'required' => ':attribute required!',
    ];

    $this->validate($request,[
        'subject' => 'required',
        'description' => 'required',
        'category' => 'required',
        'description' => 'required',
        'start' => 'required',
        'end' => 'required',
        'frequency' => 'required',
    ],$messages);

    $scheduler = new EmailScheduler();

    if($request->category ==   'Database Only') {
      $getName = Customertype::where('name', $request->category)->first();
    }
    else if($request->category ==   'Customer') {
      $getName = Customertype::where('name', $request->category)->first();
    }
    else if($request->category ==  'One Time Customer') {
      $getName = Customertype::where('name', $request->category)->first();
    }
     else {
      $getId = $request->category;
    }
    
    $scheduler->description = $request->description;
    $scheduler->subject = $request->subject;
    $scheduler->from_ = $request->from;
    $scheduler->frequency = $request->frequency;
    $scheduler->delivered = 0;

    if($request->date) {
      $scheduler->day = $request->date;
    } else {
      $scheduler->day = $request->day;
    }

    $scheduler->time = $request->time;

    if ($request->category == 'One Time Customer') {
        $scheduler->customer_type_id = $getName->id;
    }
    elseif ($request->category == 'Database Only') {
      $scheduler->customer_type_id = $getName->id;
    }
    elseif ($request->category == 'Customer') {
      $scheduler->customer_type_id = $getName->id;
    }
    else{
        $scheduler->category_id =  $getId;
    }

    $scheduler->start = Carbon::parse($request->start)->format('Y-m-d H:i:s');
    $scheduler->end = Carbon::parse($request->end)->format('Y-m-d H:i:s');
    $scheduler->save();
  
    return redirect('/email_scheduler')->with('success', 'Email has been created!');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    return view('dashboard.email_scheduler.show', [
      'title' => 'Detail Email Scheduler',
      'email_blast' => EmailScheduler::where('id', $id)->first()
    ]);
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    return view(
      'dashboard.email_scheduler.edit',
      [
        'title' => 'Edit Email Scheduler',
        'company' => Company::first(),
        'edit' => EmailScheduler::where('id', $id)->first(),
        'categories' => Category::all(),
        'customer_type' => CustomerType::all()
      ]
    );
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $validated = $request->validate([
      'subject' => ['required'],
      'description' => ['required'],
    ]);

    if ($request->category == 'Chouse Category') {
      return redirect()->back()->with('error', 'Gagal dikirim, silahkan pilih salah satu category');
    }

    $validated['subject'] = $request->subject;
    $validated['description'] = $request->description;
    if ($request->category == 'All') {
      $validated['category_id'] = null;
    } else {
      $validated['category_id'] = $request->category;
    }
    //   return response()->json($validated['category_id']);
    $validated['from_'] = $request->from;

    $email_blast = Blasting::where('id', $id)->update($validated);;

    return redirect('/email')->with('success', 'Schedule has been updated!');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    EmailScheduler::destroy($id);
    return back()->with('success', 'Row has been deleted!');
  }

}

resources/views/dashboard/email_scheduler/create.blade.php
@extends('dashboard.layouts.main')

@section('content')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2>Create Schedule</h2>
</div>

<a href="/email_scheduler" class="btn btn-danger btn-sm mb-3">
  <i class="fas fa-times-circle"></i> Cancel
</a>


@if (session('error'))
	<div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
		<strong>{{ session('error') }}</strong>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
@endif

@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
             @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
             @endforeach
        </ul>
    </div>
@endif

<form action="/email_scheduler" method="POST">
    @csrf
    <div class="row">
      <div class="col-md-12">
          <div class="row">
          <div class="form-group">
            <label for="from" class="col-sm-2 col-form-label fw-bolder">From</label>
            <div class="col-sm-12">
              <input type="text" name="from" class="form-control form-control text-center" value="{{ $company->name }}" readonly>
            </div>
          </div>
          
        </div>
        <div class="row">
          <div class="form-group">
            <label for="to" class="col-sm-2 col-form-label fw-bolder fw-bolder">Category</label>
            <div class="col-sm-12">
              <select name="category" class="form-select form-select">
                <option selected disabled>Choose Category</option>
                  <optgroup label="All Category">
                    @foreach ($customer_type as $tipe_customer)
                    <option value="{{ $tipe_customer->name }}">{{ $tipe_customer->name }}</option>
                    @endforeach
                  </optgroup>
                  <optgroup label="Category">
                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                  </select>
                <optgroup>
              @error('category')
                <div class="invalid-feedback">
                  {{ $message }}
                </div>
              @enderror
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="mb-3 row">
          <div class="form-group">
          <label for="subject" class="col-sm-2 col-form-label fw-bolder">Subject</label>
          <div class="col-sm-12">
            <input type="text" name="subject" class="form-control" value="{{ old('subject') }}" required autocomplete="off"> 
          </div>
          </div>
        </div>
        <div class="mb-3 row">
          <div class="form-group">
            <label for="description" class="col-sm-2 col-form-label fw-bolder">Description</label>
            <div class="col-sm-12">
              <textarea id="editor1" type="text" rows="6" name="description" class="form-control" required autocomplete="off">{{ old('description') }}</textarea>
            </div>
          </div>
          </div>
        </div>
    </div>

    <div class="row mb-3">
      <div class="col">
        <div class="form-group">
          <label for="input" class="col-sm-2 col-form-label fw-bolder">Start</label>
          <input id="input" name="start" width="100%" class="form-control" placeholder="Start date" value="{{ old('start') }}" required autocomplete="off">
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label for="input2" class="col-sm-2 col-form-label fw-bolder">End</label>
          <input id="input2" name="end" width="100%" class="form-control" placeholder="End date" value="{{ old('end') }}" required autocomplete="off">
        </div>
      </div>
    </div>

    <div class="form-group mb-5">
      <label for="input" class="col-sm-2 col-form-label fw-bolder">Frequency</label>
      <select class="form-select" aria-label="Default select example" name="frequency" id="frequency" onChange="opsi(this)" required>
        <option selected disabled>Choose One</option>
        <option value="daily">Daily</option>
        <option value="weekly">Weekly</option>
        <option value="monthly">Monthly</option>
      </select>
    </div>

    <div class="row">
      <div class="col">
        <div class="mb-3">
          <label for="time" class="form-label">Time</label>
          <input type="time" name="time" class="form-control @error('time') is-invalid @enderror" id="time" disabled
          value="{{ old('time') }}">
          @error('time')
            <div class="invalid-feedback">
              {{ $message }}
            </div>
          @enderror
        </div>
      </div>
      <div class="col">
        <div class="mb-3">
          <label for="day" class="form-label">day</label>
          <select class="form-select" aria-label="Default select example" name="day" id="day" disabled>
            <option selected disabled>Choose One</option>
            <option value="Sunday">Sunday</option>
            <option value="Monday">Monday</option>
            <option value="Tuesday">Tuesday</option>
            <option value="Wednesday">Wednesday</option>
            <option value="Thrusday">Thrusday</option>
            <option value="Friday">Friday</option>
            <option value="Saturday">Saturday</option>
          </select>
        </div>
      </div>
      <div class="col">
         <div class="mb-3">
      <label for="date" class="form-label">date</label>
      <input type="text" name="date" class="form-control @error('date') is-invalid @enderror" id="date" disabled
      value="{{ old('date') }}">
      @error('date')
        <div class="invalid-feedback">
          {{ $message }}
        </div>
      @enderror
    </div>
      </div>
    </div>

    <div class="row">
        <div class="col-md d-grid">
          <button type="submit" class="btn btn-primary my-4">
            <i class="fas fa-plus"></i> Create
          </button>
        </div>
    </div>
</form>
<script>
  CKEDITOR.replace( 'editor1', {
        language: 'en',
        uiColor: '#9AB8F3',
        filebrowserUploadUrl: '{{route('email_scheduler.store', ['_token' => csrf_token() ])}}',
        filebrowserUploadMethod: 'form'
  });
  
   $('#input').datetimepicker({ uiLibrary: 'bootstrap4', modal: true, footer: true });
   $('#input2').datetimepicker({ uiLibrary: 'bootstrap4', modal: true, footer: true });

   function opsi(value){

    var frequency = $("#frequency").val();
    if(frequency == "daily"){
      document.getElementById("time").disabled = false;
    } else {
      document.getElementById("time").disabled = true;
    }

    if(frequency == "weekly"){
      document.getElementById("day").disabled = false;
      document.getElementById("time").disabled = false;
    } else {
      document.getElementById("day").disabled = true;
    }

    if(frequency == "monthly"){
      document.getElementById("date").disabled = false;
      document.getElementById("time").disabled = false;
    } else {
      document.getElementById("date").disabled = true;
    }

  }
</script>    
@endsection

resources/views/dashboard/email_scheduler/edit.blade.php
@extends('dashboard.layouts.main')

@section('content')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h2>Create Schedule</h2>
</div>

<a href="/email_scheduler" class="btn btn-danger btn-sm mb-3">
  <i class="fas fa-times-circle"></i> Cancel
</a>


@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
             @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
             @endforeach
        </ul>
    </div>
@endif


<form action="/email_scheduler" method="POST">
    @csrf
    <div class="row">
      <div class="col-md-12">
          <div class="row">
          <div class="form-group">
            <label for="from" class="col-sm-2 col-form-label fw-bolder">From</label>
            <div class="col-sm-12">
              <input type="text" name="from" class="form-control form-control text-center" value="{{ $company->name }}" readonly>
            </div>
          </div>
          
        </div>
        <div class="row">
          <div class="form-group">
            <label for="to" class="col-sm-2 col-form-label fw-bolder fw-bolder">Category</label>
            <div class="col-sm-12">
              <select name="category" class="form-select form-select">
                <option selected disabled>Choose Category</option>
                  <optgroup label="All Category">
                    @foreach ($customer_type as $tipe_customer)
                    <option value="{{ $tipe_customer->name }}">{{ $tipe_customer->name }}</option>
                    @endforeach
                  </optgroup>
                  <optgroup label="Category">
                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                  </select>
                <optgroup>
              @error('category')
                <div class="invalid-feedback">
                  {{ $message }}
                </div>
              @enderror
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="mb-3 row">
          <div class="form-group">
          <label for="subject" class="col-sm-2 col-form-label fw-bolder">Subject</label>
          <div class="col-sm-12">
            <input type="text" name="subject" class="form-control" value="{{ $edit->subject }}" required autocomplete="off"> 
          </div>
          </div>
        </div>
        <div class="mb-3 row">
          <div class="form-group">
            <label for="description" class="col-sm-2 col-form-label fw-bolder">Description</label>
            <div class="col-sm-12">
              <textarea type="text" id="editor1" rows="6" name="description" class="form-control" required autocomplete="off">{{ $edit->description }}</textarea>
            </div>
          </div>
          </div>
        </div>
    </div>

    <div class="row mb-3">
      <div class="col">
        <div class="form-group">
          <label for="input" class="col-sm-2 col-form-label fw-bolder">Start</label>
          <input id="input" name="start" width="100%" class="form-control" placeholder="Start date" value="{{ old('start') }}" required autocomplete="off">
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <label for="input2" class="col-sm-2 col-form-label fw-bolder">End</label>
          <input id="input2" name="end" width="100%" class="form-control" placeholder="End date" value="{{ old('end') }}" required autocomplete="off">
        </div>
      </div>
    </div>

    <div class="form-group mb-5">
      <label for="input" class="col-sm-2 col-form-label fw-bolder">Frequency</label>
      <select class="form-select" aria-label="Default select example" name="frequency" id="frequency" onChange="opsi(this)" required>
        <option selected disabled>Choose One</option>
        <option value="daily">Daily</option>
        <option value="weekly">Weekly</option>
        <option value="monthly">Monthly</option>
      </select>
    </div>

    <div class="row">
      <div class="col">
        <div class="mb-3">
          <label for="time" class="form-label">Time</label>
          <input type="time" name="time" class="form-control @error('time') is-invalid @enderror" id="time" disabled
          value="{{ old('time') }}">
          @error('time')
            <div class="invalid-feedback">
              {{ $message }}
            </div>
          @enderror
        </div>
      </div>
      <div class="col">
        <div class="mb-3">
          <label for="day" class="form-label">day</label>
          <select class="form-select" aria-label="Default select example" name="day" id="day" disabled>
            <option selected disabled>Choose One</option>
            <option value="Sunday">Sunday</option>
            <option value="Monday">Monday</option>
            <option value="Tuesday">Tuesday</option>
            <option value="Wednesday">Wednesday</option>
            <option value="Thrusday">Thrusday</option>
            <option value="Friday">Friday</option>
            <option value="Saturday">Saturday</option>
          </select>
        </div>
      </div>
      <div class="col">
         <div class="mb-3">
      <label for="date" class="form-label">date</label>
      <input type="text" name="date" class="form-control @error('date') is-invalid @enderror" id="date" disabled
      value="{{ old('date') }}">
      @error('date')
        <div class="invalid-feedback">
          {{ $message }}
        </div>
      @enderror
    </div>
      </div>
    </div>

    <div class="row">
        <div class="col-md d-grid">
          <button type="submit" class="btn btn-primary my-4">
            <i class="fas fa-plus"></i> Create
          </button>
        </div>
    </div>
</form>
<script>
  CKEDITOR.replace( 'editor1', {
        language: 'en',
        uiColor: '#9AB8F3'
    });

   $('#input').datetimepicker({ uiLibrary: 'bootstrap4', modal: true, footer: true });
   $('#input2').datetimepicker({ uiLibrary: 'bootstrap4', modal: true, footer: true });

   function opsi(value){
    var frequency = $("#frequency").val();

    if(frequency == "daily"){
      document.getElementById("time").disabled = false;
    } else {
      document.getElementById("time").disabled = true;
    }

    if(frequency == "weekly"){
      document.getElementById("day").disabled = false;
      document.getElementById("time").disabled = false;
    } else {
      document.getElementById("day").disabled = true;
    }

    if(frequency == "monthly"){
      document.getElementById("date").disabled = false;
      document.getElementById("time").disabled = false;
    } else {
      document.getElementById("date").disabled = true;
    }

    }
</script>    
@endsection

resources/views/dashboard/email_scheduler/index.blade.php
@extends('dashboard.layouts.main')

@section('content')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2 text-center">Email Scheduler</h1>
</div>

<a href="/email_scheduler/create" class="btn btn-primary mb-3">
	<i class="fas fa-plus"></i> Create Schedule
</a>

@if (session('success'))
	<div class="alert alert-success alert-dismissible fade show text-center" role="alert">
		<strong>{{ session('success') }}</strong>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
@endif

<div class="table-responsive">
	<table class="table table-striped table-sm">
		<thead>
			<tr>
				<th scope="col">Category</th>
				<th scope="col">Subject</th>
                {{-- <th scope="col" width="10%">Delivered</th> --}}
				<th scope="col">Frequency</th>
				<th scope="col">Day</th>
				<th scope="col">Every Hour</th>
				<th scope="col">Start_at</th>
				<th scope="col">End_at</th>
				<th scope="col">Action</th>
			</tr>
		</thead>
		<tbody>
			@foreach ($email_scheduler as $item)
			<tr>
				<form action="/email/sendEmail" class="d-inline" method="POST">
					@csrf
				<td>
					@if ($item->category == null)
					{{ $item->customerType->name ?? $item->category->name }}
					@else
					{{ $item->category->name ?? $item->customerType->name  }}
					@endif
				</td>
				<td>{{ $item->subject }}</td>
                {{-- <td>
                    <input type="text" class="form-control form-control-sm bg-transparent border-0" value="{{ $item->delivered == 1 ? 'Yes' : 'No' }}" name="description" readonly >
                </td> --}}
				<td>{{ $item->frequency }}</td>
				<td>{{ $item->day ?? "-" }}</td>
				<td>{{ $item->time ?? "null" }}</td>
				<td>{{ date('d M Y - h:i', strtotime($item->start))}}</td>
				<td>{{ date('d M Y - h:i', strtotime($item->end))}}</td>
				<td>
                </form>
					<a href="/email_scheduler/{{ $item->id }}" class="btn btn-info btn-sm"><i class="far fa-eye"></i></a>
					<a href="/email_scheduler/{{ $item->id }}/edit" class="btn btn-warning btn-sm"><i class="far fa-edit"></i></a>
					<form action="/email_scheduler/{{ $item->id }}" method="POST" class="d-inline">
						@method('delete')
						@csrf
						<button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')"><i class="fas fa-trash"></i></button>
					</form>
				</td>
			</tr>
			@endforeach
		</tbody>
	</table>
</div>

@endsection